name: CI Tests

on:
  push:
    branches: [ "**" ] # Run on pushes to all branches
  pull_request:
    branches: [ main ] # Run on pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest # Use the latest available Bun version

    - name: Install dependencies
      run: bun install --frozen-lockfile # Ensures consistent installs based on lockfile

    - name: Run tests
      run: bun run test # Executes the 'test' script from your package.json
