name: CI Tests

on:
  push:
    branches: ["**"] # Run on pushes to all branches
  pull_request:
    branches: [main] # Run on pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use Node.js LTS version 20.x

      - name: Install dependencies
        run: npm install # Use npm to install dependencies

      - name: Run tests
        # Run tap via npx. The runner will automatically fail the step on non-zero exit codes.
        run: npx tap test/**/*.test.ts
