name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main # Trigger for production deployments
      - staging # Trigger for staging deployments
  workflow_dispatch: # Allows manual triggering

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }} # e.g., us-central1
  GCP_ARTIFACT_REGISTRY_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }} # e.g., odyssey-backend-images
  IMAGE_NAME_BASE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }}/odyssey-backend

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # e.g., projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} # e.g., github-actions-deployer@aura-fitness-457121.iam.gserviceaccount.com
          # Fallback to SA Key if WIF is not set up (less secure)
          # create_credentials_file: true
          # credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t "${{ env.IMAGE_NAME_BASE }}:${{ github.sha }}" .

      - name: Push Docker image to Artifact Registry
        run: docker push "${{ env.IMAGE_NAME_BASE }}:${{ github.sha }}"

  deploy_staging:
    name: Deploy to Staging Cloud Run
    needs: build_and_push_image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Though not strictly needed for deploy if image is already built

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          # create_credentials_file: true
          # credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Staging Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_STAGING }} \
            --image "${{ env.IMAGE_NAME_BASE }}:${{ github.sha }}" \
            --region "${{ env.GCP_REGION }}" \
            --platform managed \
            --project "${{ env.GCP_PROJECT_ID }}" \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production,SUPABASE_URL=${{ secrets.STAGING_SUPABASE_URL }},SUPABASE_SERVICE_ROLE_KEY=${{ secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }},GEMINI_API_KEY=${{ secrets.STAGING_GEMINI_API_KEY }}" \
            `# Add other staging-specific env vars here, comma-separated` \
            --quiet

  deploy_production:
    name: Deploy to Production Cloud Run
    needs: build_and_push_image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          # create_credentials_file: true
          # credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Production Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_PROD }} \
            --image "${{ env.IMAGE_NAME_BASE }}:${{ github.sha }}" \
            --region "${{ env.GCP_REGION }}" \
            --platform managed \
            --project "${{ env.GCP_PROJECT_ID }}" \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production,SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }},SUPABASE_SERVICE_ROLE_KEY=${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }},GEMINI_API_KEY=${{ secrets.PROD_GEMINI_API_KEY }}" \
            `# Add other production-specific env vars here, comma-separated` \
            --quiet
